version: '2'
services:
    web-api:
        container_name: web-api
        build:
          context: .
          dockerfile: Dockerfile

    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
         - "9090:8080"
        volumes:
         - ./proxy.conf:/etc/nginx/conf.d/default.conf